### ISSUE TITLE
Problem with setdebugmode.sh and CC-2014

### ISSUE THREAD

**Issue by kouma** [davidderaedt/CC-Extension-Builder-for-Sublime-Text#6]
Hi, 

just installed your extension and it seems you forgot to update the path in setdebugmode.sh file. 
"~/Library/Preferences/com.adobe.CSXS.4.plist" should be "~/Library/Preferences/com.adobe.CSXS.5.plist".

It is causing a "Unable to load" error when trying to display the extension panel (debug mode not active) with the new version (CSXS 5.0).

Hope it helps ;)

**Comment by kouma** [comment]
Note : I've updated my own .plist "by hand" with xcode and it went alright.

**Comment by davidderaedt** [comment]
This was fixed weeks ago, it looks like an issue is on the git side (I love those). Investigating as we speak...

**Comment by davidderaedt** [comment]
This is fixed now that I re-sync'd the SDK. Thanks for the heads up!
